package com.community.hundred.common.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.community.hundred.modules.manager.entry.BookEntry;
import com.community.hundred.modules.manager.entry.UserEntry;

import com.community.hundred.common.greendao.BookEntryDao;
import com.community.hundred.common.greendao.UserEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookEntryDaoConfig;
    private final DaoConfig userEntryDaoConfig;

    private final BookEntryDao bookEntryDao;
    private final UserEntryDao userEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookEntryDaoConfig = daoConfigMap.get(BookEntryDao.class).clone();
        bookEntryDaoConfig.initIdentityScope(type);

        userEntryDaoConfig = daoConfigMap.get(UserEntryDao.class).clone();
        userEntryDaoConfig.initIdentityScope(type);

        bookEntryDao = new BookEntryDao(bookEntryDaoConfig, this);
        userEntryDao = new UserEntryDao(userEntryDaoConfig, this);

        registerDao(BookEntry.class, bookEntryDao);
        registerDao(UserEntry.class, userEntryDao);
    }
    
    public void clear() {
        bookEntryDaoConfig.clearIdentityScope();
        userEntryDaoConfig.clearIdentityScope();
    }

    public BookEntryDao getBookEntryDao() {
        return bookEntryDao;
    }

    public UserEntryDao getUserEntryDao() {
        return userEntryDao;
    }

}
